- name: Avi Deploy new virtual
  include_role:
    name: avinetworks.aviconfig
  vars:
    cloud_name: "Default-Cloud"
    tenant_name: "admin"
    app_name: "{{ ApplicationName }}"
    app_type: "{{ ApplicationType }}"
    env: "{{ Environment }}"
    avi_controller: "{{ ctrl }}"
    location: "{{ loc }}"
    department: "{{ Department }}"
    pool_name: "{{ PoolName }}"
    pool_members: "{{  PoolMembers.split('::') }}"
    avi_config_state: "present"
    avi_username: "{{ aws_tower_username }}"
    avi_password: "{{ aws_tower_password }}"
    api_version: "{{ avi_version }}"
    aws_subnet: "{{ aws_network_ref }}"
    tmp_avi_config: "{{ lookup('template','templates/vs_create.j2') | from_yaml }}"
    avi_config: "{{tmp_avi_config.avi_config }}"